### ISSUE TITLE
Trouble when following docs for dividing a design history into sections

### ISSUE THREAD

**Issue by benilovj** [fofr/govuk-design-history#86]
I ran into a bit of trouble when [following the instructions for dividing the design history into sections](https://design-history.herokuapp.com/divide-a-design-history-into-different-sections/).

I ended up copying how the [BAT design history](https://bat-design-history.netlify.app/) is set up, which worked. Here's the change I ended up making in the end: https://github.com/DFE-Digital/teacher-id-design-history/pull/5/commits/212cb131dcf5da82cb7f1936b842bebccb1352e6

It's worth calling out that our design history app is using node 16 – I dunno if that plays a part.

Both issues appear to be tag-related

## Issue with `tags: false` in the section index file

The frontmatter line `tags: false` in the section markdown file caused the following error:

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] > boolean false is not iterable (cannot read property Symbol(Symbol.iterator))

`TypeError` was thrown:
[11ty]     TypeError: boolean false is not iterable (cannot read property Symbol(Symbol.iterator))
        at new Set (<anonymous>)
        at Function.cleanupData (/Users/benilovj/workspace/teacher-id-design-history/node_modules/@11ty/eleventy/src/TemplateData.js:596:23)
        at Template.getFrontMatterData (/Users/benilovj/workspace/teacher-id-design-history/node_modules/@11ty/eleventy/src/TemplateContent.js:198:25)
        at async Template.getData (/Users/benilovj/workspace/teacher-id-design-history/node_modules/@11ty/eleventy/src/Template.js:366:29)
        at async Template.getTemplateMapEntries (/Users/benilovj/workspace/teacher-id-design-history/node_modules/@11ty/eleventy/src/Template.js:979:33)
        at async TemplateMap.add (/Users/benilovj/workspace/teacher-id-design-history/node_modules/@11ty/eleventy/src/TemplateMap.js:59:21)
        at async Promise.all (index 7)
        at async TemplateWriter._createTemplateMap (/Users/benilovj/workspace/teacher-id-design-history/node_modules/@11ty/eleventy/src/TemplateWriter.js:242:5)
        at async TemplateWriter.generateTemplates (/Users/benilovj/workspace/teacher-id-design-history/node_modules/@11ty/eleventy/src/TemplateWriter.js:276:5)
        at async TemplateWriter.write (/Users/benilovj/workspace/teacher-id-design-history/node_modules/@11ty/eleventy/src/TemplateWriter.js:322:23)
[11ty] Wrote 0 files in 0.02 seconds (v1.0.0-canary.44)
```

I ended up removing it from the file.

## Issue when omitting tag override in the section index file

If the `tags: false` line was omitted, I saw the following error:

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] > Dependency Cycle Found: ___TAG___all -> ./app/posts/find-your-trn/find-your-trn.md -> ___TAG___find-your-trn -> ./app/posts/find-your-trn/find-your-trn.md

`Error` was thrown:
[11ty]     Error: Dependency Cycle Found: ___TAG___all -> ./app/posts/find-your-trn/find-your-trn.md -> ___TAG___find-your-trn -> ./app/posts/find-your-trn/find-your-trn.md
        at /Users/benilovj/workspace/teacher-id-design-history/node_modules/dependency-graph/lib/dep_graph.js:43:17
        at /Users/benilovj/workspace/teacher-id-design-history/node_modules/dependency-graph/lib/dep_graph.js:292:11
        at Array.forEach (<anonymous>)
        at DepGraph.overallOrder (/Users/benilovj/workspace/teacher-id-design-history/node_modules/dependency-graph/lib/dep_graph.js:291:14)
        at TemplateMap.getMappedDependencies (/Users/benilovj/workspace/teacher-id-design-history/node_modules/@11ty/eleventy/src/TemplateMap.js:143:18)
        at TemplateMap.cache (/Users/benilovj/workspace/teacher-id-design-history/node_modules/@11ty/eleventy/src/TemplateMap.js:332:30)
        at TemplateWriter._createTemplateMap (/Users/benilovj/workspace/teacher-id-design-history/node_modules/@11ty/eleventy/src/TemplateWriter.js:243:28)
        at async TemplateWriter.generateTemplates (/Users/benilovj/workspace/teacher-id-design-history/node_modules/@11ty/eleventy/src/TemplateWriter.js:276:5)
        at async TemplateWriter.write (/Users/benilovj/workspace/teacher-id-design-history/node_modules/@11ty/eleventy/src/TemplateWriter.js:322:23)
        at async Eleventy.executeBuild (/Users/benilovj/workspace/teacher-id-design-history/node_modules/@11ty/eleventy/src/Eleventy.js:958:13)
[11ty] Wrote 0 files in 0.03 seconds (v1.0.0-canary.44)
```

It was fixed by adding:

```
override:tags:
  - post
```

**Comment by benilovj** [comment]
Thanks @paulrobertlloyd

**Comment by rinto-c** [comment]
This is ace @benilovj. It was such a frustration not being able to solve this, but thanks.
